### ISSUE TITLE
socket.error: illegal IP address string passed to inet_aton

### ISSUE THREAD

**Issue by nnfewl** [bdamele/icmpsh#5]
socket.error: illegal IP address string passed to inet_aton???
![image](https://user-images.githubusercontent.com/24603835/37242510-a75ba4cc-24a5-11e8-8e01-afaf37e3e744.png)

**Comment by johnjohny1990** [comment]
I have same problem

**Comment by slayerlab** [comment]
Look at this commit: https://github.com/inquisb/icmpsh/commit/e62cd2a2409778643f9abc664cda64bebda6f4ab

Obs: check if you have a "python-impacket" library installed.

via "advanced packaging tool" (apt):
`apt install python-impacket`

or python
`pip install impacket`

**Comment by myxss** [comment]
![image](https://user-images.githubusercontent.com/33475775/113957957-cda7d280-9852-11eb-98ca-6730ef155af8.png)

**Comment by slayerlab** [comment]
@myxss Have you already checked the commit https://github.com/bdamele/icmpsh/commit/e62cd2a2409778643f9abc664cda64bebda6f4ab?
